config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#new'

  resources :users, only: %i[index create show]

  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  resources :questions, only: %i[index create show] do
    post 'vote/up' => 'question_vote#up'
    post 'vote/down' => 'question_vote#down'

    resources :answers, only: %i[create]

    post 'answers/:id/vote/up' => 'answer_vote#up', as: 'answer_vote_up'
    post 'answers/:id/vote/down' => 'answer_vote#down', as: 'answer_vote_down'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Ownable

  belongs_to :question
end

app/models/answer_vote.rb
class AnswerVote < ApplicationRecord
  include Votable

  belongs_to :answer

  alias_attribute :votable_id, :answer_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/ownable.rb
module Ownable
  extend ActiveSupport::Concern

  included do
    belongs_to :user, default: lambda {
      User.create_with(email: 'guest@askmate.com',
                       password_digest: BCrypt::Password.create(SecureRandom.uuid))
          .find_or_create_by!(username: 'Anonymous')
    }
  end

end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    belongs_to :user

    enum direction: { down: -1, neutral: 0, up: 1 }
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Ownable

  has_many :answers, dependent: :destroy
end

app/models/question_vote.rb
class QuestionVote < ApplicationRecord
  include Votable

  belongs_to :question

  alias_attribute :votable_id, :question_id
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_secure_password
end

app/controllers/answer_vote_controller.rb
class AnswerVoteController < ApplicationController
  include VotableController

  before_action :set_votable

  private

  def set_votable
    @votable = AnswerVote
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params.merge(user_id: @current_user&.id))

    redirect_to question_path(@answer.question) if @answer.save
  end

  private

  def answer_params
    params.require(:answer).permit(:message, :image, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/concerns/votable_controller.rb
module VotableController
  extend ActiveSupport::Concern

  def up
    save :up if current_user
  end

  def down
    save :down if current_user
  end

  def save(vote_direction)
    @votable.where(votable_id: params[:votable_id], user_id: @current_user.id)
            .first_or_create!.tap do |vote|
      vote.direction = vote_direction
      vote.save
    end
  end

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).limit(5)
  end

  def temp
    redirect_to root_path
  end
end

app/controllers/question_vote_controller.rb
class QuestionVoteController < ApplicationController
  include VotableController

  before_action :set_votable

  private

  def set_votable
    @votable = QuestionVote
    params[:votable_id] = params[:question_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @question.increment!(:views)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params.merge(user_id: @current_user&.id))

    redirect_to @question if @question.save
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :message, :image)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.find_by_username(params[:user][:username])
    if @user&.authenticate(params[:user][:password])
      session[:user_id] = @user.id
    else
      flash[:error] = 'Invalid username or password.'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    session[:user_id] = nil
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = if request.get?
              User.new
            else
              User.new(user_params)
            end
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      errors = user.errors.full_messages
      if errors.find { |message| /confirmation doesn't match/ =~ message }
        flash[:signup_error] = 'Passwords must match.'
      elsif errors.find { |message| /has already been taken/ =~ message }
        flash[:signup_error] = 'Username or email already in use.'
      end
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email,
                                 :password, :password_confirmation, :birthday)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_tag question_answers_path(question_id), class: 'collapsible' do %>
  <label for="message">Answer:</label>
  <textarea id="message" name="answer[message]" cols="55" rows="8" minlength="10" required></textarea>
  <br><br>
  <label for="image">Image URL:</label>
  <input type="url" id="image" name="answer[image]" size="30">
  <%= hidden_field_tag 'answer[question_id]', question_id %>
  <br><br>
  <button type="submit" class="input">Submit answer</button>
  <button type="reset" class="input">Reset</button>

  <br><br>
<% end %>

app/views/questions/_form.html.erb
<div id="form-container">
  <%= form_tag controller: :questions, action: :create do %>
    <label for="title">Question title:</label>
    <input type="text" id="title" name="question[title]" minlength="5" size="30" required>
    <label for="message">Detailed description:</label>
    <textarea id="message" name="question[message]" cols="55" rows="8" required></textarea>
    <label for="image">Image URL:</label>
    <input type="url" id="image" name="question[image]" size="30">
    <br>
    <button type="submit" class="input">Submit question</button>
    <button type="reset" class="input">Reset</button>
  <% end %>
</div>

app/views/questions/_index.html.erb
<div class="slide-container">
  <%= render 'questions/new' %>
  <div class="question">
    <div class="tag"><h3><%= title %></h3></div>
    <% if questions %>
      <% questions.each do |question| %>
        <%= render 'questions/show', question: question %>
      <% end %>
    <% else %>
      <p>Sorry, there are no such questions.</p><br>
    <% end %>
  </div>
  <% if questions %>
    <div class="list"><a href="#top" class="to-top">Back to top</a></div>
  <% end %>
</div>

app/views/questions/_new.html.erb
<%= render 'questions/form', question: @question || Question.new %>

app/views/questions/_show.html.erb
<div class="question-container">
  <div class="header">
    <h2><%= link_to question.title, question %></h2>
  </div>
  <div class="vote-container">
    <span title="{{ question['vote_value'] }}" class="vote-value"></span>
    <%= form_tag question_vote_up_path(question_id: question.id),
                 class: "vote-up", remote: true, authenticity_token: true do %>
      <button type="button" class="vote-btn-up"><i class="fa fa-caret-up"></i></button>
    <% end %>
    <p><%= question.upvotes %></p>
    <%= form_tag question_vote_down_path(question_id: question.id),
                 class: "vote-down", remote: true, authenticity_token: true do %>
      <button type="button" class="vote-btn-down"><i class="fa fa-caret-down"></i></button>
    <% end %>
  </div>
  <p><%= question.message %></p>
  <% if question.image %>
    <%= image_tag question.image %>
  <% end %>
  <div class="footer">
    <%= link_to user_path(question.user) do %>
      <p><%= question.user.username %></p>
    <% end %>
    <p><%= time_ago_in_words question.created_at %> ago</p>
    <p>Views: <%= question.views %></p>
  </div>
</div>

app/views/questions/index.html.erb
<div class="page-body">
  <div class="slide-container">
    <%= render 'questions/new' %>
    <div class="tag_container">
      <div class="tag">
        <h3>All questions</h3>
      </div>
    </div>
  </div>
  <div class="table_container">
    <table>
      <tr>
        <th>
          <%= link_to 'Posted', questions_path(sortby: :created_at) %>
        </th>
        <th>
          <%= link_to 'Title', questions_path(sortby: :title) %>
        </th>
        <th>
          <%= link_to questions_path(sortby: :upvotes) do %>
            <i class="fa fa-thumbs-up" aria-hidden="true" title="upvotes"></i>
          <% end %>
        </th>
        <th>
          <%= link_to questions_path(sortby: :answers) do %>
            <i class="fa fa-comment" aria-hidden="true" title="answers"></i>
          <% end %>
        </th>
        <th>
          <%= link_to questions_path(sortby: :views) do %>
            <i class="fa fa-eye" aria-hidden="true" title="views"></i>
          <% end %>
        </th>
      </tr>
      <% @questions.each do |question| %>
        <tr class="table_body">
          <td><%= time_ago_in_words question.created_at %> ago</td>
          <td><%= link_to question.title, question %></td>
          <td><%= question.upvotes %></td>
          <td><%= question.answers.size %></td>
          <td><%= question.views %></td>
        </tr>
      <% end %>
    </table>
    <br>
    <a href="#top" class="to-top">Back to top</a>
  </div>
  <%= render 'layouts/login-box' %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="page-body">
  <div class="slide-container">
    <%= render 'questions/new' %>
    <div class="question">
      <%= render 'questions/show', question: @question %>
    </div>
    <div class="answer-button"><p>Post answer</p></div>
    <%= render 'answers/form', question_id: @question.id %>
  </div>
  <div class="answer-container">
    <div class="answer-grid">
      <% @question.answers.each do |answer| %>
      <div class="answer">
        <div class="vote-container">
          <span title="{{ answer['vote_value'] }}" class="vote-value"></span>
          <%= form_tag question_answer_vote_up_path(question_id: @question.id, id: answer.id),
                       class: "vote-up", remote: true, authenticity_token: true do %>
            <%= hidden_field_tag 'votable_id', answer.id %>
            <button type="button" class="vote-btn-up">
              <i class="fa fa-caret-up"></i>
            </button>
          <% end %>
          <p><%= answer.upvotes %></p>
          <%= form_tag question_answer_vote_down_path(question_id: @question.id, id: answer.id),
                       class: "vote-down", remote: true, authenticity_token: true do %>
            <%= hidden_field_tag 'votable_id', answer.id %>
            <button type="button" class="vote-btn-down">
              <i class="fa fa-caret-down"></i>
            </button>
          <% end %>
        </div>
        <div class="answer-message"><p><%= answer.message %></p></div>
        <% if answer.image %>
          <%= image_tag answer.image %>
        <% end %>
        <div class="footer">
          <p><%= time_ago_in_words answer.created_at %> ago</p>
          <%= link_to user_path(answer.user) do %>
            <p><%= answer.user.username %></p>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <% if @question.answers.size < 2 %>
      <div class="padding"></div>
    <% else %>
      <br>
      <a href="#top" class="to-top">Back to top</a>
    <% end %>
  </div>
  <%= render 'layouts/login-box' %>
</div>

app/views/users/index.html.erb
<div class="page-body">
  <div class="slide-container">
    <%= render 'questions/new' %>
    <div class="tag_container">
      <div class="tag">
        <h3>Ask mates</h3>
      </div>
    </div>
  </div>
  <div class="table_container">
    <table>
      <tr>
        <th>Username</th>
        <th>Full name</th>
        <th>Birth date</th>
        <th><i class="fa fa-question"></i></th>
        <th><i class="fa fa-comment" aria-hidden="true"></i></th>
      </tr>
      <% @users.each do |user| %>
        <tr class="table_body">
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= "#{user.first_name} #{user.last_name}" %></td>
          <td><%= user.birthday %></td>
          <td><%= user.questions.size %></td>
          <td><%= user.answers.size %></td>
        </tr>
      <% end %>
    </table>
    <br>
    <a href="#top" class="to-top">Back to top</a>
  </div>
  <%= render 'layouts/login-box' %>
</div>

app/views/users/new.html.erb
<div class="page-body">
  <div class="slide-container">
    <%= render 'questions/new' %>
    <div class="registration">
      <div class="tag"><h3>Registration</h3></div>
      <%= form_for(@user) do %>
        <label for="new_username">Username:<p class="red inline"> *</p></label>
        <input type="text" name="user[username]" id="new_username" value="<%= @user.username %>" required>
        <label for="new_password">Password:<p class="red inline"> *</p></label>
        <input type="password" name="user[password]" id="new_password" required>
        <label for="confirm_password">Confirm password:<p class="red inline"> *</p></label>
        <input type="password" name="user[password_confirmation]" id="confirm_password" required>
        <label for="email">E-mail address:<p class="red inline"> *</p></label>
        <input type="email" name="user[email]" id="email" required>
        <label for="firstname">First name:</label>
        <input type="text" name="user[first_name]" id="firstname">
        <label for="lastname">Last name:</label>
        <input type="text" name="user[last_name]" id="lastname">
        <label for="birthdate">Birthday:</label>
        <input type="date" name="user[birthday]" id="birthdate">
        <br>
        <button class="input" type="submit">Register</button>

        <% if flash[:signup_error] %>
          <p class="red"><%= flash[:signup_error] %></p>
        <% end %>

      <% end %>
    </div>
  </div>
  <%= render 'layouts/login-box' %>
</div>

app/views/users/show.html.erb
<div class="page-body">
  <div class="slide-container">
    <%= render 'questions/new' %>
    <div class="route-container">
      <p>
        > <%= link_to 'Users', users_path %>
        > <%= @user.username %>
      </p>
    </div>
    <div class="tag_container">
      <div class="tag">
        <h3><%= @user.username %>'s question(s)</h3>
      </div>
      <% if @user.questions.empty? %>
        <p><%= @user.username %> has no questions yet.</p>
      <% end %>
    </div>
  </div>
  <% unless @user.questions.empty? %>
    <div class="table_container">
      <table>
        <tr>
          <th>Submission time</th>
          <th>Question title</th>
          <th>Votes</th>
          <th><i class="fa fa-eye" aria-hidden="true"></i></th>
        </tr>

        <% @user.questions.each do |question| %>

          <tr class="table_body">
            <td><%= time_ago_in_words question.created_at %> ago</td>
            <td><%= link_to question.title, question %></td>
            <td><%= question.upvotes %></td>
            <td><%= question.views %></td>
          </tr>

        <% end %>

      </table>
    </div>
  <% end %>



  <div class="table_container2">
    <div class="tag_container">
      <div class="tag">
        <h3><%= @user.username %>'s answer(s)</h3>
      </div>
      <% if @user.answers.empty? %>
        <p><%= @user.username %> has no answers yet.</p>
      <% end %>
    </div>
    <% unless @user.answers.empty? %>
      <table>
        <tr>
          <th>Submission time</th>
          <th>Answer</th>
          <th>Votes</th>
        </tr>

        <% @user.answers.each do |answer| %>
          <tr class="table_body">
            <td><%= time_ago_in_words answer.created_at %> ago</td>
            <td><%= link_to answer.message, question_path(answer.question) %></td>
            <td><%= answer.upvotes %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
    <br>
    <a href="#top" class="to-top">Back to top</a>
  </div>
  <%= render 'layouts/login-box' %>
</div>